{{- $uiContext := (merge dict . .Values.ui) -}}
{{- $apiContext := (merge dict . .Values.api) -}}
{{- $accountConsoleUrl := (include "osie.ui.accountConsoleUrl" .) -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "osie.componentName" $uiContext }}
  labels:
    {{- include "osie.labels" $uiContext | nindent 4 }}
spec:
  replicas: {{ $uiContext.replicaCount }}
  selector:
    matchLabels:
      {{- include "osie.selectorLabels" $uiContext | nindent 6 }}
  template:
    metadata:
      {{- with $uiContext.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "osie.labels" $uiContext | nindent 8 }}
    spec:
      {{- with $uiContext.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml $uiContext.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-{{ $uiContext.component }}
          securityContext:
            {{- toYaml $uiContext.securityContext | nindent 12 }}
          image: "{{ $uiContext.image.repository }}:{{ $uiContext.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ $uiContext.image.pullPolicy }}
          env:
            - name: OSIE_OAUTH2_ISSUER
              value: {{ include "osie.ui.oauth2IssuerUri" . }}
            - name: OSIE_OAUTH2_CLIENT_ID
              value: {{ include "osie.oauth2ClientId" $uiContext }}
            - name: OSIE_OAUTH2_AUDIENCE
              value: {{ include "osie.oauth2Audience" $uiContext | quote }}
            - name: OSIE_OAUTH2_SCOPE
              value: {{ include "osie.oauth2Scope" $uiContext | quote }}
            - name: OSIE_OAUTH2_LOGOUT_URL
              value: {{ include "osie.oauth2LogoutUrl" $uiContext | quote }}
            - name: OSIE_API_HOST
              value: https://{{ include "osie.ingressHostname" $apiContext }}
            - name: OSIE_API_PREFIX
              value: /api-v1
            {{- if $accountConsoleUrl }}
            - name: OSIE_OAUTH2_USER_ACCOUNT_CONSOLE
              value: {{ $accountConsoleUrl }}
            {{- end }}
            {{- if not $uiContext.oauth2.pkce.enabled }}
            - name: OSIE_OAUTH2_DISABLE_PKCE
              value: "true"
            {{- end}}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml $uiContext.resources | nindent 12 }}
      {{- with $uiContext.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $uiContext.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $uiContext.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
